_wandb:
    value:
        cli_version: 0.22.3
        e:
            za4l6g4t6qjkuuymmko51n94no6j53ds:
                args:
                    - --batch_size
                    - "2"
                    - --accum_iter
                    - "8"
                    - --model
                    - learnable_vec1024x16_dim1024_depth24_nb
                    - --point_cloud_size
                    - "8192"
                    - --input_dim
                    - "13"
                    - --epochs
                    - "400"
                    - --data_path
                    - /scratch/project_2016517/junjie/dataset/repaired_npz
                    - --output_dir
                    - output/ae/phase1_production_v4
                    - --log_dir
                    - output/ae/phase1_production_v4
                    - --blr
                    - "2e-4"
                    - --warmup_epochs
                    - "20"
                    - --wandb
                codePath: VecSetX/vecset/main_ae.py
                codePathLocal: VecSetX/vecset/main_ae.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: c15919822199@gmail.com
                executable: /projappl/project_2016517/JunjieCheng/junjieenv/bin/python3
                git:
                    commit: 98792635a6539f177638c928df323995cc14f5c0
                    remote: https://github.com/Junjiecheng2024/VecSetX
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-658fb5a3-de42-d59c-6b66-c1f1eb2f3a4a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-268602de-8bad-ef3d-0265-a1a8db69f4a8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-dfcdf753-a478-9c98-a0c3-1f1efbd5edb0
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-b485df15-ae77-114f-815b-ef818721ab00
                host: g2201.mahti.csc.fi
                memory:
                    total: "540285788160"
                os: Linux-4.18.0-553.74.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /projappl/project_2016517/JunjieCheng/VecSetX/VecSetX/vecset/main_ae.py
                python: CPython 3.12.11
                root: /projappl/project_2016517/JunjieCheng/VecSetX
                slurm:
                    job_id: "5540424"
                    mpi_type: pmix_v3
                startedAt: "2025-12-07T20:19:50.130593Z"
                writerId: za4l6g4t6qjkuuymmko51n94no6j53ds
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.11
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
accum_iter:
    value: 8
batch_size:
    value: 2
blr:
    value: 0.0002
clip_grad:
    value: null
data_path:
    value: /scratch/project_2016517/junjie/dataset/repaired_npz
device:
    value: cuda
dist_backend:
    value: nccl
dist_eval:
    value: false
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: true
epochs:
    value: 400
eval:
    value: false
gpu:
    value: 0
input_dim:
    value: 13
layer_decay:
    value: 0.75
local_rank:
    value: -1
log_dir:
    value: output/ae/phase1_production_v4
lr:
    value: null
min_lr:
    value: 1e-06
model:
    value: learnable_vec1024x16_dim1024_depth24_nb
num_workers:
    value: 60
output_dir:
    value: output/ae/phase1_production_v4
pin_mem:
    value: false
point_cloud_size:
    value: 8192
rank:
    value: 0
resume:
    value: null
seed:
    value: 0
start_epoch:
    value: 0
wandb:
    value: true
warmup_epochs:
    value: 20
weight_decay:
    value: 0.05
world_size:
    value: 4
