_wandb:
    value:
        cli_version: 0.22.3
        e:
            ufrv80g1gpar98pjnfx67xxvalyapp54:
                args:
                    - --batch_size
                    - "2"
                    - --accum_iter
                    - "8"
                    - --model
                    - learnable_vec1024x16_dim1024_depth24_nb
                    - --point_cloud_size
                    - "8192"
                    - --input_dim
                    - "13"
                    - --epochs
                    - "400"
                    - --data_path
                    - /scratch/project_2016517/junjie/dataset/repaired_npz
                    - --output_dir
                    - output/ae/phase1_production_v4
                    - --log_dir
                    - output/ae/phase1_production_v4
                    - --blr
                    - "2e-4"
                    - --warmup_epochs
                    - "20"
                    - --wandb
                codePath: VecSetX/vecset/main_ae.py
                codePathLocal: VecSetX/vecset/main_ae.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: c15919822199@gmail.com
                executable: /projappl/project_2016517/JunjieCheng/junjieenv/bin/python3
                git:
                    commit: e937f78923ed6341408e1d9b3d5290889fd267a4
                    remote: https://github.com/Junjiecheng2024/VecSetX
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-658fb5a3-de42-d59c-6b66-c1f1eb2f3a4a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-268602de-8bad-ef3d-0265-a1a8db69f4a8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-dfcdf753-a478-9c98-a0c3-1f1efbd5edb0
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-b485df15-ae77-114f-815b-ef818721ab00
                host: g2201.mahti.csc.fi
                memory:
                    total: "540285788160"
                os: Linux-4.18.0-553.74.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /projappl/project_2016517/JunjieCheng/VecSetX/VecSetX/vecset/main_ae.py
                python: CPython 3.12.11
                root: /projappl/project_2016517/JunjieCheng/VecSetX
                slurm:
                    cluster_name: mahti
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "128"
                    cpus_per_task: "32"
                    gpus_on_node: "4"
                    gtids: "0"
                    hint: nomultithread
                    job_account: project_2016526
                    job_cpus_per_node: "128"
                    job_end_time: "1765308282"
                    job_gid: "10033029"
                    job_gpus: 0,1,2,3
                    job_id: "5541348"
                    job_name: vecset_phase1_v2
                    job_nodelist: g2201
                    job_num_nodes: "1"
                    job_partition: gpumedium
                    job_qos: normal
                    job_start_time: "1765178682"
                    job_uid: "10033029"
                    job_user: chengjun
                    jobid: "5541348"
                    localid: "0"
                    mem_per_node: "490000"
                    mpi_type: pmix_v3
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: g2201
                    nprocs: "4"
                    ntasks: "4"
                    ntasks_per_node: "4"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /projappl/project_2016517/JunjieCheng/VecSetX/VecSetX
                    submit_host: mahti-login12.mahti.csc.fi
                    task_pid: "3612708"
                    tasks_per_node: "4"
                    threads_per_core: "1"
                    topology_addr: root_switch.lisw2203.g2201
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=32
                startedAt: "2025-12-08T07:26:07.453064Z"
                writerId: ufrv80g1gpar98pjnfx67xxvalyapp54
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.11
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
accum_iter:
    value: 8
batch_size:
    value: 2
blr:
    value: 0.0002
clip_grad:
    value: null
data_path:
    value: /scratch/project_2016517/junjie/dataset/repaired_npz
device:
    value: cuda
dist_backend:
    value: nccl
dist_eval:
    value: false
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: true
epochs:
    value: 400
eval:
    value: false
gpu:
    value: 0
input_dim:
    value: 13
layer_decay:
    value: 0.75
local_rank:
    value: -1
log_dir:
    value: output/ae/phase1_production_v4
lr:
    value: null
min_lr:
    value: 1e-06
model:
    value: learnable_vec1024x16_dim1024_depth24_nb
num_workers:
    value: 60
output_dir:
    value: output/ae/phase1_production_v4
pin_mem:
    value: false
point_cloud_size:
    value: 8192
rank:
    value: 0
resume:
    value: null
seed:
    value: 0
start_epoch:
    value: 0
wandb:
    value: true
warmup_epochs:
    value: 20
weight_decay:
    value: 0.05
world_size:
    value: 4
