_wandb:
    value:
        cli_version: 0.22.3
        e:
            w6n41bodf6t7c2esj8vesroib2dpht2k:
                args:
                    - --batch_size
                    - "2"
                    - --accum_iter
                    - "8"
                    - --model
                    - learnable_vec1024x16_dim1024_depth24_nb
                    - --point_cloud_size
                    - "8192"
                    - --input_dim
                    - "13"
                    - --epochs
                    - "800"
                    - --data_path
                    - /scratch/project_2016517/junjie/dataset/repaired_npz
                    - --output_dir
                    - output/ae/phase1_production
                    - --log_dir
                    - output/ae/phase1_production
                    - --wandb
                codePath: VecSetX/vecset/main_ae.py
                codePathLocal: VecSetX/vecset/main_ae.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: c15919822199@gmail.com
                executable: /projappl/project_2016517/JunjieCheng/junjieenv/bin/python
                git:
                    commit: 8e08f46e65f8ed13f2725b79d6b3852a94052a61
                    remote: https://github.com/Junjiecheng2024/VecSetX
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-c14cf888-8958-46c8-00b2-edbab614211c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-aa845a4c-338c-f51b-35f2-5c335bb129ad
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-2efc8229-13da-a856-e6d2-1cd68e2e37e8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-dc89cde7-edc8-1398-4278-bd4bdbf5be86
                host: g3301.mahti.csc.fi
                memory:
                    total: "540285173760"
                os: Linux-4.18.0-553.74.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /projappl/project_2016517/JunjieCheng/VecSetX/VecSetX/vecset/main_ae.py
                python: CPython 3.10.14
                root: /projappl/project_2016517/JunjieCheng/VecSetX
                slurm:
                    cluster_name: mahti
                    conf: /etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000000000000000000000000000000000000000000000000000000300000000
                    cpu_bind_list: "0x0000000000000000000000000000000000000000000000000000000300000000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "128"
                    cpus_per_task: "32"
                    distribution: cyclic
                    gpus_on_node: "4"
                    gtids: "0"
                    hint: nomultithread
                    job_account: project_2016526
                    job_cpus_per_node: "128"
                    job_end_time: "1764869113"
                    job_gid: "10033029"
                    job_gpus: 0,1,2,3
                    job_group: pepr_chengjun
                    job_id: "5525125"
                    job_name: vecset_phase1
                    job_nodelist: g3301
                    job_num_nodes: "1"
                    job_partition: gpumedium
                    job_qos: normal
                    job_start_time: "1764739513"
                    job_uid: "10033029"
                    job_user: chengjun
                    jobid: "5525125"
                    launch_node_ipaddr: 10.141.11.15
                    localid: "0"
                    mem_per_node: "490000"
                    mpi_type: pmix_v3
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: g3301
                    nprocs: "4"
                    ntasks: "4"
                    ntasks_per_node: "4"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "35349"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "38403"
                    pty_win_col: "162"
                    pty_win_row: "21"
                    script_context: prolog_task
                    srun_comm_host: 10.141.11.15
                    srun_comm_port: "35747"
                    step_gpus: "1"
                    step_id: "0"
                    step_launcher_port: "35747"
                    step_nodelist: g4301
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 13409-13410
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /projappl/project_2016517/JunjieCheng/VecSetX/VecSetX
                    submit_host: g4301.mahti.csc.fi
                    task_pid: "3137719"
                    tasks_per_node: "4"
                    threads_per_core: "1"
                    topology_addr: root_switch.lisw3303.g3301
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=32
                startedAt: "2025-12-03T05:26:48.005341Z"
                writerId: w6n41bodf6t7c2esj8vesroib2dpht2k
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.14
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
accum_iter:
    value: 8
batch_size:
    value: 2
blr:
    value: 0.0001
clip_grad:
    value: null
data_path:
    value: /scratch/project_2016517/junjie/dataset/repaired_npz
device:
    value: cuda
dist_backend:
    value: nccl
dist_eval:
    value: false
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: true
epochs:
    value: 800
eval:
    value: false
gpu:
    value: 0
input_dim:
    value: 13
layer_decay:
    value: 0.75
local_rank:
    value: -1
log_dir:
    value: output/ae/phase1_production
lr:
    value: null
min_lr:
    value: 1e-06
model:
    value: learnable_vec1024x16_dim1024_depth24_nb
num_workers:
    value: 60
output_dir:
    value: output/ae/phase1_production
pin_mem:
    value: false
point_cloud_size:
    value: 8192
rank:
    value: 0
resume:
    value: null
seed:
    value: 0
start_epoch:
    value: 0
wandb:
    value: true
warmup_epochs:
    value: 40
weight_decay:
    value: 0.05
world_size:
    value: 4
